#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
    #[ "$f" -ne "/etc/X11/xinit/xinitrc.d/30-dbus" ] && [ -x "$f" ] && . "$f"
  done
  unset f
fi

eval "$(gpg-agent --daemon)" &

feh --bg-scale Arch.jpg & 

## now being started from .bash_profile, YES, I login to console now.
#sh ~/.tmuxer& # start tmux with 3 sessions  

# starts a urxvt deamon and starts an instance of urxvtc
urxvtd -q -o -f && urxvtc -e tmux attach &

xrdb -merge $HOME/.Xresources &

# exec gnome-session
# exec startkde
# exec startxfce4 --with-ck-launch
# ...or the Window Manager of your choice
#exec ck-launch-session gnome-session

if [[ $1 == "gnome" ]] 
then
    exec ck-launch-session gnome-session
elif [[ $1 == "xfce" ]] 
then
    exec startxfce4 --with-ck-launch
elif [[ $1 == "dwm" ]] 
then
    exec dwm
elif [[ $1 == "i3" ]] 
then
    exec ck-launch-session i3
else
    exec ck-launch-session i3
fi
