#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
    #[ "$f" -ne "/etc/X11/xinit/xinitrc.d/30-dbus" ] && [ -x "$f" ] && . "$f"
  done
  unset f
fi

#eval "$(gpg-agent --daemon)" &
eval `/usr/bin/ssh-agent`

if test -f /usr/lib/ssh/x11-ssh-askpass # Archlinux
then
        SSH_ASKPASS=/usr/lib/ssh/x11-ssh-askpass ssh-add < /dev/null
fi

feh --bg-scale Arch.jpg & 
#exec dwm

## now being started from .bash_profile, YES, I login to console now.

#sh ~/.tmuxer& # start tmux with 3 sessions  

# starts a urxvt deamon and starts an instance of urxvtc
#urxvtd -q -o -f  &

#xrdb -merge $HOME/.Xresources &

# exec gnome-session
# exec startkde
# exec startxfce4 --with-ck-launch
# ...or the Window Manager of your choice
#exec ck-launch-session gnome-session

#echo $@

#if [[ $2 == "gnome" ]] 
#then
#    exec ck-launch-session gnome-session
#elif [[ $2 == "xfce" ]] 
#then
#    exec startxfce4 --with-ck-launch
#elif [[ $2 == "dwm" ]] 
#then
#    exec dwm
#elif [[ $2 == "i3" ]] 
#then
#    exec ck-launch-session dbus-launch i3
#else
#    exec ck-launch-session gnome-session
#fi
